server:
  port: 8110

spring:
  application:
    name: IR-Core
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 192.168.181.129:8848
#        register-enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/IR?useUnicode=true&characterEncoding=UTF-8&useSSL=false&useAffectedRows=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: admin123
  redis:
#    host: 192.168.181.129
    host: 127.0.0.1
    port: 6379
    database: 0
#    password: 123456 #默认为空
    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0


mybatis-plus: #mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    keyId: LTAI5tCa3gsrrKZngPpv53se
    keySecret: 2g7y5CYi4yDe8FtY5NS1N9tQGOprW3
    bucketName: campus-help-picture

ir:
  thread:
    coreSize: 10
    maxSize: 20
    keepAliveTime: 30


#server:
#  port: 8110 # 服务端口
#spring:
#  profiles:
#    active: dev # 环境设置
#  application:
#    name: DIV-core # 服务名
#  datasource: # mysql数据库连接
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/div_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
#    username: root
#    password: LSSw135353079..
#  redis:
#    host: 192.168.181.130
#    port: 6379
#    database: 0
#    password: 123456 #默认为空
#    timeout: 3000ms #最大等待时间，超时则抛出异常，否则请求一直等待
#    lettuce:
#      pool:
#        max-active: 20  #最大连接数，负值表示没有限制，默认8
#        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
#        max-idle: 8     #最大空闲连接，默认8
#        min-idle: 0     #最小空闲连接，默认0
#
#mybatis-plus: #mybatis
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  Dao-locations: classpath:com/XHY/DIV/core/Dao/xml/*.xml
#
#aliyun:
#  oss:
#    endpoint: oss-cn-beijing.aliyuncs.com
#    keyId: LTAI5tLAUYNKmPj7cbMJPsEp
#    keySecret: ae6y6bxR4ZWBnw5ly0uVzEItb4k5VL
#    bucketName: divgood
